version: '3'

x-common: &common
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile.dev
  image: stimulus-drag-drop:1.0.0
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
  tmpfs:
    - /tmp

services:
  bash:
    <<: *common
    command: bash
